brcm_github_pat: ENC[AES256_GCM,data:Qdut4EP9i9mH2gpbBmM/2cjUYuLw+lrjiySLOYGMBOZVJ407zG2GTVtjKbL987/n3+D1AutIWxdWbT+xcCvQ68+WyWPmrvQhkvRmVAIBWapO22yYJjcXefRR6m/3,iv:nnSKjahrD0TLLoTrvmA5O0o9MH16QBc4yXy03Yp8mMA=,tag:g9D5daFj2AXN9yJZLZlL3g==,type:str]
sops:
    age:
        - recipient: age16g6rms7ctp9n564mf9a0skrt32rwarjmwgjn7r330csx2epmlqqqekjs6v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRllJRjhkT2RvQlFsaUN6
            YW5JOVJKd2c2OWlOdm1TZ2g4Rkl0WEIxclhnClVMdE1OUDh1RllZZDF3eGdxZGFZ
            K2lQM0ZEMFVydnFtY1pWcFBBQkhpUVkKLS0tIGd6dmMwUVQ5WWlVcmlJV091M1JC
            QnFCbk9PeUQ1N0JJcFM4MzBEVHhDNG8KN1AgI05b5O3glevtpoGqVJuz3Hrxojo5
            GI1kjf/FmdMJ8vTc6INckunj0W3PhgJ9vGHi1twxFCE+op2tLCAO5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gp0ej2304v6zdvenys25r4wz8ryprfms5mam0k9ak03xc8uesfpq3r5rux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMUQxb3RZZFRuSGdrWkIy
            Sk40R0thWEFHNVdVT25VOXFKY3ovaGRNTTNFCk9kRzN5Zkh0TDNoOHM2QjFCRHhL
            NGwyV1RsVU5JMVFoSFJ3QjV6SFRwZmsKLS0tIFdlZCs0QzNTOCtRVTcwZ2RsNW5P
            SmpEZGRiaXFsRk4yWTV4cHAvZ0NTcWsKM7bvl0xAhiPn2lAHUE1IbSci0dW2tnTZ
            NTQqi8Je7z0/KCl4fDtbjWHbKAEtTtw+NFXsUXBvd8q8PzxW3+VPBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T14:42:37Z"
    mac: ENC[AES256_GCM,data:GxRcd4FXjuUDDs8dRxTcFQpJ9ffGd2agIWp5SIiGD4CJs4D6ISCdTCRG6LUUfSBZb0phN9R1EuQ2CeKWBhSaw2eBh7+87nbptfC7t01d3/Wz3EdMuNwjUsTvUczoQBJB5B7kYTRII5ntfqPXb91Ae3ELxOKtSz/NhxezNHT4yfc=,iv:0nBvCdzAthArLfnLeL+VdbFQ0TnU7JuNGjOIWSdtpx0=,tag:W1qXt60mhBgxfDo7nPuG0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
